# .github/workflows/trigger-repo-a.yml
name: Trigger Repo A Workflow

on:
  workflow_dispatch:  # Or whatever trigger Repo B uses

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Repo B workflow running"

  trigger-repo-a:
    needs: build
    uses: Buckwich/ci-target/.github/workflows/blank.yml@main
    with: {}
    secrets: inherit
